language: python

services:
  - docker

before_install:
  - docker build -t "tvecs" -f Dockerfile .
  - docker run -it tvecs py.test
  - docker run -d -p 5000:5000 tvecs

script:
  - curl 127.0.0.1:5000