language: python
sudo: required
cache: pip
python:
  - "2.7_with_system_site_packages"
before_install:
  - "sudo apt-get install -qq gfortran libblas-dev liblapack-dev python-scipy"
# command to install dependencies
install: 
  - "pip install -r requirements.txt"
  - "python setup.py install"
# command to run tests
script: pytest