language: python
cache: pip
sudo: required
addons:
  apt:
    packages:
      - gfortran
      - libgfortran3
virtualenv:
  system_site_packages: true
env:
  matrix:
    - PYTHON_VERSION="2.7" SCIPY_VERSION="0.17.1" SKLEARN_VERSION="0.17.1"
install:
  - "source CI/install.sh"
  - "pip install -r requirements.txt"
  - "python CI/download_tokenizer.py"
# command to run tests
script:
  - "py.test tests/*.py"