language: python
cache: pip
virtualenv:
  system_site_packages: true
env:
  matrix:
    - PYTHON_VERSION="2.7" SCIPY_VERSION="0.14.0" SKLEARN_VERSION="0.15.2"
    - PYTHON_VERSION="3.4" LATEST="true"
install:
  - "source CI/install.sh"
  - "pip install -r requirements.txt"
  - "python CI/download_tokenizer.py"
  - "python setup.py install"
# command to run tests
script: py.test