language: python
cache: pip
sudo: required
addons:
  apt:
    packages:
      - gfortran
      - libgfortran3
virtualenv:
  system_site_packages: true
env:
  matrix:
    - PYTHON_VERSION="3.6" SCIPY_VERSION="1.5.2" SKLEARN_VERSION="0.23.2"
install:
  - "source CI/install.sh"
  - "pip install -r requirements.txt"
  - "python CI/download_tokenizer.py"
# command to run tests
script:
  - "py.test tests/*.py"